{
  imports = [
    ./nix.nix
    ./locale.nix
    ./user.nix
    ./impermanence.nix
    ./hardware
    ./network
    ./kernel
    ./wayland
    ./theme
    ./audio
    ./logging.nix
    ./ssh.nix
    ./keyd.nix
    ./btrfs.nix
    ./firefox.nix
    ./command-line.nix
    ./chezmoi.nix
    ./packages/gui.nix
    ./terminals.nix
  ];
}
