add_newline = false
command_timeout = 100
format = "$hostname$username$directory$shell$nix_shell$git_branch$git_commit$git_state$git_status$nix$c$python$lua$rust$jobs$cmd_duration$container\n$character"
palette = "catppuccin_mocha"
scan_timeout = 2

[c]
detect_files = ["Makefile"]

[character]
error_symbol = "[[󰋕](bold #f38ba8) ❯](bold #f38ba8)"
format = "$symbol "
success_symbol = "[[󰋕](bold #a6e3a1) ❯](bold #b4befe)"

[directory]
format = "[ ](bold #a6e3a1) [$path]($style) "
home_symbol = "󰋜 ~"
read_only = "  "
read_only_style = "197"
style = "purple"
truncation_length = 6

[directory.substitutions]
"~/Dev" = "dev"
"~/Documents" = "Docs"

[git_commit]
commit_hash_length = 7

[git_status]
ahead = "⇡ "
behind = "⇣ "
conflicted = " "
deleted = "✘ "
diverged = "⇆ "
modified = "!"
renamed = "»"
staged = "+"
stashed = "≡"
untracked = "?"

[hostname]
disabled = false
format = "@[$hostname](bold #89b4fa) "
ssh_only = true

[line_break]
disabled = false

[nix_shell]
heuristic = true
symbol = "  "

[package]
symbol = "  "

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[username]
format = "[$user]($style) in "
