[main]
box-drawings-uses-font-glyphs=yes
locked-title=no
shell=nu
font=JetBrainsMono Nerd Font:size=14

[cursor]
style=beam
beam-thickness=2

[bell]
urgent=yes
notify=no
command=/run/current-system/sw/bin/notify-send --app-name foot --icon foot --urgency normal --expire-time 5000 -- Bell
command-focused=yes
[key-bindings]
show-urls-launch=Control+Shift+u
unicode-input=Control+Shift+i
# search-start=Control+f


[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
inhibit-when-focused=no

[colors-dark]

cursor=ffffff 44df44
foreground=ffffff
background=0d0e1c
selection-foreground=ffffff
selection-background=7030af
urls=c6daff

regular0=000000
regular1=ff5f59
regular2=44bc44
regular3=d0bc00
regular4=2fafff
regular5=feacd0
regular6=00d3d0
regular7=a6a6a6

bright0=595959
bright1=ff6b55
bright2=00c06f
bright3=fec43f
bright4=79a8ff
bright5=f78fe7
bright6=6ae4b9
bright7=ffffff

16=fec43f
17=ff9f80
