theme = "modus"

[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
completion-trigger-len = 1
cursorline = true
file-picker.hidden = false
indent-guides.render = true
line-number = "relative"
lsp.display-inlay-hints = true
lsp.inlay-hints-length-limit = 20
rulers = [80]
scrolloff = 8
soft-wrap.enable = true
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.whitespace.characters]
newline = "↴"
tab = "⇥"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
backspace = "rotate_view"
S-backspace = "rotate_view_reverse"
D = "kill_to_line_end"
V = ["extend_to_line_bounds", "select_mode", "trim_selections"]
X = ["extend_to_line_bounds", "trim_selections"]
esc = ["collapse_selection", "keep_primary_selection"]
ret = "goto_word"
"A-tab" = "goto_next_buffer"
"A-S-tab" = "goto_previous_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.normal.space]
R = "rename_symbol"
q = ":bc"
r = "replace_selections_with_clipboard"
x = "extend_to_line_bounds"

[keys.normal.space.c]
f = ":format"
y = ":yank-diagnostic"

[keys.normal.space.space]
a = ":reload-all"
f = """:sh nu ~/.config/helix/scripts/yazi.nu "%{file_path_absolute}" "%{workspace_directory}" "%{current_working_directory}" > /dev/null"""
j = ":sh bash ~/.config/helix/scripts/jjui.sh"
r = ":sh bash ~/.config/helix/scripts/scooter.sh"

[keys.normal.space.t]
W = ":set whitespace.render none"
w = ":set whitespace.render all"

[keys.select]
ret = "goto_word"

[keys.select.space]
r = "replace_selections_with_clipboard"

[keys.select.space.space]
u = ":pipe-to nu ~/.config/helix/scripts/function-usages.nu --selection --lang %{language}"

[keys.select.space.space.r]
r = ":pipe-to bash ~/.config/helix/scripts/scooter.sh --selection"
