theme = "cat"

[editor]
# shell = ["nu", "--commands"]
color-modes = true
completion-replace = true
completion-trigger-len = 1
cursorline = true
file-picker.hidden = false
indent-guides.render = true
line-number = "relative"
lsp.display-inlay-hints = true
lsp.inlay-hints-length-limit = 20
soft-wrap.enable = true
trim-final-newlines = true
trim-trailing-whitespace = true
bufferline = "multiple"
# rulers = [100]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.whitespace.characters]
newline = "↴"
tab = "⇥"


[keys.normal]
backspace = "rotate_view"
S-backspace = "rotate_view_reverse"
D = "kill_to_line_end"
X = "select_line_above"
ret = "goto_word"
S-tab = "rotate_view_reverse"
"A-tab" = "goto_next_buffer"
"A-S-tab" = "goto_previous_buffer"
esc = ["collapse_selection", "keep_primary_selection"]
[keys.normal.space]
x = "extend_to_line_bounds"
q = ":bc"

[keys.normal.space.t]
w = ":set whitespace.render all"
W = ":set whitespace.render none"

[keys.normal.space.c]
f = ":format"
y = ":yank-diagnostic"

[keys.normal.space.space]
f = """:sh nu ~/.config/helix/scripts/yazi.nu "%{file_path_absolute}" "%{workspace_directory}" "%{current_working_directory}" > /dev/null"""
r = ":sh bash ~/.config/helix/scripts/scooter.sh"
j = ":sh bash ~/.config/helix/scripts/jjui.sh"
a = ":reload-all"

[keys.select]
ret = "goto_word"

[keys.select.space.space]
u = ":pipe-to nu ~/.config/helix/scripts/function-usages.nu --selection --lang %{language}"

[keys.select.space.space.r]
r = ":pipe-to bash ~/.config/helix/scripts/scooter.sh --selection"
