use-grammars = { only = [
  "nix",
  "ghostty",
  "ini",
  "toml",
  "asm",
  "c",
  "cpp",
  "bash",
  "python",
  "json",
  "jsonc",
  "yaml",
  "markdown",
  "kdl",
] }


[[language]]
name = "toml"
auto-format = true


[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }


[[language]]
name = "kdl"
auto-format = false
formatter = { command = "kdlfmt", args = ["format", "-"] }
