windowrule = match:float true, decorate false
windowrule = border_color rgb(ff5555),match:xwayland true # check if window is xwayland

windowrule = match:title ^(Open File)(.*)$, center on, float on
windowrule = match:title ^(Select a File)(.*)$, center on, float on
windowrule = match:title ^(Open Folder)(.*)$, center on, float on
windowrule = match:title ^(Save As)(.*)$, center on, float on
windowrule = match:title ^(Library)(.*)$, center on, float on
windowrule = match:title ^(File Upload)(.*)$, center on, float on
windowrule = match:title ^(.*)(wants to save)$, center on, float on
windowrule = match:title ^(.*)(wants to open)$, center on, float on

windowrule = match:class ^(pavucontrol|org.pulseaudio.pavucontrol)$, float on, size 45% 45%, center on

windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on, keep_aspect_ratio on, move 73% 72%, size 25% 25%, pin on

windowrule = match:title ^(firefox-nightly — Sharing Indicator)$, workspace special silent
windowrule = match:title ^(.*is sharing (your screen|a window).)$, workspace special silent

windowrule = match:title ^(.*(Disc|WebC)ord.*)$, workspace 6
windowrule = match:class neovide, workspace 1
windowrule = match:class ^(obsidian)$, workspace 2
windowrule = match:class ^(firefox.*)$, opacity 1.0 override


windowrule = match:class foot, float on, size 1000 1000, center on
windowrule = match:class foot.yazi, float on, size 1600 1000, center on
windowrule = match:class ^(chrome-.*__-Default)$, float on, center on
windowrule = match:class ^(claude)$, float on, size 40% 40%, center on

windowrule = match:class .*(confirm|pavucontrol|cpupower|xdg-desktop-portal-gtk).*, tag +dialog
windowrule = match:title .*(Extension.*Bitwarden).*, tag +dialog
windowrule = match:tag dialog, float on, size 45% 45%, center on


windowrule = no_dim on, match:class com.mitchellh.ghostty

layerrule = blur on, match:namespace launcher
layerrule = ignore_alpha 0.5, match:namespace launcher
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.69, match:namespace notifications

layerrule = no_anim on, match:namespace launcher
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace overview
layerrule = no_anim on, match:namespace noanim




workspace = special:special, gapsout:20

workspace = 5, layout:scrolling

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1, default:true
workspace = 3, monitor:DP-1, default:true
workspace = 4,  monitor:DP-1, default:true
workspace = 5, monitor:HDMI-A-1, default:true
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1, default:true
workspace = 8, monitor:HDMI-A-1, default:true

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]
