active_tab_font_style bold
allow_remote_control yes
bold_font        auto
bold_italic_font auto
confirm_os_window_close 1
cursor_beam_thickness 2
cursor_blink_interval 0
cursor_shape beam
cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 2
enabled_layouts tall:bias=50;full_size=1;mirrored=false
focus_follows_mouse yes
font_family      family="JetBrainsMono Nerd Font"
font_size 12
hide_window_decorations yes
inactive_tab_font_style normal
inactive_text_alpha 0.7
italic_font      auto
linux_display_server wayland
listen_on unix:@kitty
mouse_hide_wait 0
notify_on_cmd_finish unfocused 5
scrollback_fill_enlarged_window yes
scrollback_lines 10000
shell fish
tab_bar_edge top
tab_bar_style slant
update_check_interval 0

clear_all_shortcuts yes
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab -1
map alt+[ previous_window
map alt+] next_window
map alt+enter launch --location=vsplit --cwd=current
map ctrl+alt+d close_window_with_confirmation ignore-shell
map alt+space toggle_layout stack
map alt+t command_palette
map alt+tab next_tab
map alt+w next_window
map ctrl++ change_font_size all +1.0
map ctrl+- change_font_size all -1.0
map ctrl+0 change_font_size all 0
map ctrl+alt+[ move_tab_backward
map ctrl+alt+] move_tab_forward
map ctrl+alt+b detach_window new-tab
map ctrl+alt+w layout_action bias 50 62 70
map ctrl+alt+j layout_action decrease_num_full_size_windows
map ctrl+alt+k layout_action increase_num_full_size_windows
map ctrl+alt+m layout_action mirror toggle
map ctrl+alt+o detach_window ask
map ctrl+alt+shift+o detach_tab ask
map ctrl+enter launch --type=tab --cwd=current
map ctrl+equal change_font_size all +1.0
map ctrl+/ search_scrollback
map ctrl+shift+- show_last_command_output
map ctrl+shift+c copy_to_clipboard
map ctrl+s show_scrollback
map ctrl+shift+p command_palette
map ctrl+shift+u open_url_with_hints
map ctrl+shift+v paste_from_clipboard



# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# Scrollbar colors
scrollbar_handle_color  #9399b2
scrollbar_track_color   #45475a

# URL color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8
