active_tab_font_style bold
allow_remote_control yes
listen_on unix:@kitty
clear_all_shortcuts yes
confirm_os_window_close 0
cursor_beam_thickness 2
cursor_blink_interval 0
cursor_shape beam
shell nu
enable_audio_bell no
enabled_layouts tall:bias=50;full_size=1;mirrored=false
focus_follows_mouse yes
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14
inactive_tab_font_style normal
inactive_text_alpha 0.7
mouse_hide_wait 0
hide_window_decorations yes
scrollback_fill_enlarged_window yes
scrollback_lines 10000
tab_bar_edge top
tab_bar_style slant
update_check_interval 0
notify_on_cmd_finish unfocused 10

linux_display_server wayland

cursor_trail 1
cursor_trail_start_threshold 2
cursor_trail_decay 0.1 0.3

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab -1
map alt+[ previous_window
map alt+] next_window
map alt+enter launch --location=vsplit --cwd=current
map alt+q close_window_with_confirmation ignore-shell
map alt+space toggle_layout stack
map alt+t command_palette
map alt+tab next_tab
map alt+w next_window
map ctrl++ change_font_size all +1.0
map ctrl+- change_font_size all -1.0
map ctrl+0 change_font_size all 0
map ctrl+alt+[ move_tab_backward
map ctrl+alt+] move_tab_forward
map ctrl+alt+enter detach_window new-tab
map ctrl+alt+h layout_action bias 50 62 70
map ctrl+alt+j layout_action decrease_num_full_size_windows
map ctrl+alt+k layout_action increase_num_full_size_windows
map ctrl+alt+m layout_action mirror toggle
map ctrl+alt+o detach_window ask
map ctrl+alt+shift+o detach_tab ask
map ctrl+enter launch --type=tab --cwd=current
map ctrl+equal change_font_size all +1.0
map ctrl+f search_scrollback
map ctrl+g show_last_command_output
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+h show_scrollback
map ctrl+shift+p command_palette
map ctrl+shift+u open_url_with_hints
map ctrl+shift+v paste_from_clipboard
