GOPATH=${XDG_DATA_HOME}/go
GNUPGHOME=${XDG_DATA_HOME}/gnupg
NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
NPM_CONFIG_INIT_MODULE=${XDG_CONFIG_HOME}/npm/config/npm-init.js
RIPGREP_CONFIG_PATH=${XDG_CONFIG_HOME}/ripgrep/config
PATH=${HOME}/.local/bin:${HOME}/architect/scripts:${PATH}
TERMINAL=xdg-terminal-exec
