sandbox_mode = "workspace-write"
approval_policy = "on-request"
personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "medium"

[projects."/home/wasd/.config/nvim"]
trust_level = "trusted"

[projects."/home/wasd"]
trust_level = "trusted"

[projects."/home/wasd/.local/share/chezmoi"]
trust_level = "trusted"

[projects."/home/wasd/architect"]
trust_level = "trusted"

[projects."/home/wasd/linix"]
trust_level = "trusted"

[tui]
theme = "monokai-extended-origin"

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-21T21:34:41Z"
source_type = "local"
source = "/home/wasd/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[features]
terminal_resize_reflow = true
