#!/usr/bin/env bash
set -euo pipefail

BOOK_DIR="$HOME/misc/books"
cd "$BOOK_DIR" || exit 1

selection=$(fd --type f --extension pdf --extension epub | fuzzel --dmenu --prompt='Open Book: ' --width=80 --lines=24)

if [ -n "$selection" ]; then
  sioyek "$selection" &
fi
