hl.on("hyprland.start", function()
	hl.exec_cmd("app2unit -t service eww daemon --no-daemonize")
	hl.exec_cmd("app2unit pypr")
	hl.exec_cmd("foot --server")
	hl.exec_cmd("app2unit -t service wallpaper")
	hl.exec_cmd("app2unit wl-paste --type text --watch cliphist store")
	hl.exec_cmd("app2unit wl-paste --type image --watch cliphist store")
	hl.dispatch(hl.dsp.focus({ workspace = 1 }))
	hl.exec_cmd("sh -c 'sleep 0.5; app2unit eww open workspace-indicator'")
end)
