palette = "dracula"

add_newline = false

command_timeout = 1000

format = """$os$directory$git_branch$git_status$c$lua$zig$python$rust$nix_shell
$character"""

[os]
format = '[󰣇](bold blue) '
disabled = false

[os.symbols]
Arch = '󰣇'

[character]
success_symbol = "[λ](fg:green)"
error_symbol = "[ λ](fg:red)"
vimcmd_symbol = "[  ❮](bold fg:green)"
vimcmd_visual_symbol = "[  ▼](bold fg:yellow)"
vimcmd_replace_symbol = "[  ](bold fg:purple)"
vimcmd_replace_one_symbol = "[  ](bold fg:purple)"
format = "$symbol "

[directory]
truncation_length = 5
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only = '  '
format = '[@](bold purple) [$path]($style)[$read_only]($read_only_style) '
style = "bold purple"
read_only_style = "red"

[git_branch]
symbol = ""
format = '[on](text) [$symbol $branch]($style) '
style = 'bold green'

[git_status]
format = '([$all_status$ahead_behind]($style)) '
style = 'bold green'
conflicted = '[🏳](red)'
untracked = '[?](orange)'
ahead = '[⇡${count}](green)'
behind = '[⇣${count}](green)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](red)'
stashed = '[](pink)'
modified = '[](yellow)'
staged = '[+](green)'
renamed = '[»](orange)'
deleted = '[-](red)'

[c]
style = " fg:blue"
detect_files = ["CMakeLists.txt", "compile_commands.json"]
disabled = false
symbol = " "

[nix_shell]
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [ $state( \($name\))](bold blue) '

[rust]
symbol = " "

[python]
symbol = " "

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
