palette = "catppuccin_mocha"

add_newline = false

command_timeout = 1000

format = """$os$directory$git_branch$git_status$c$lua$zig$python$rust$nix_shell
$character"""

[os]
format = '[󰣇](bold blue) '
disabled = false

[os.symbols]
Arch = '󰣇'

[character]
success_symbol = "[λ](fg:green)"
error_symbol = "[ λ](fg:red)"
vimcmd_symbol = "[  ❮](bold fg:green)"
vimcmd_visual_symbol = "[  ▼](bold fg:yellow)"
vimcmd_replace_symbol = "[  ](bold fg:mauve)"
vimcmd_replace_one_symbol = "[  ](bold fg:mauve)"
format = "$symbol "

[directory]
truncation_length = 5
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only = '  '
format = '[@](bold mauve) [$path]($style)[$read_only]($read_only_style) '
style = "bold mauve"
read_only_style = "red"

[git_branch]
symbol = ""
format = '[on](text) [$symbol $branch]($style) '
style = 'bold green'

[git_status]
format = '([$all_status$ahead_behind]($style)) '
style = 'bold green'
conflicted = '[🏳](red)'
untracked = '[?](peach)'
ahead = '[⇡${count}](green)'
behind = '[⇣${count}](green)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](red)'
stashed = '[](pink)'
modified = '[](yellow)'
staged = '[+](green)'
renamed = '[»](peach)'
deleted = '[-](red)'

[c]
style = "fg:blue"
detect_files = ["CMakeLists.txt", "compile_commands.json"]
disabled = false
symbol = " "

[nix_shell]
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [ $state( \($name\))](bold blue) '

[rust]
symbol = " "

[python]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
