add_newline = false
command_timeout = 100
format = "[┏](bold frame)$status$cmd_duration[━](bold frame) $hostname$directory$nix_shell${custom.jj}$package$c$python$lua$rust$jobs$container\n$character"
palette = "modus"
scan_timeout = 2

[c]
detect_files = ["Makefile"]
format = "[$symbol$version]($style) "
style = "bold context"

[character]
error_symbol = "[┃ 󰘧](bold error)"
format = "$symbol "
success_symbol = "[┃ 󰘧](bold frame)"
vimcmd_symbol = "[┃ 󰘧](bold prompt)"

[cmd_duration]
format = "[┫](bold frame)[$duration](bold duration)[┣](bold frame)"
min_time = 2000
show_milliseconds = false

[container]
format = "[$symbol$name]($style) "
style = "bold context"

[custom.jj]
format = "$output "
shell = ["jj-starship"]
when = "jj-starship detect"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"
read_only = " "
read_only_style = "warning"
style = "bold path"
truncate_to_repo = false
truncation_length = 100

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[hostname]
disabled = false
format = "[@$hostname](bold remote) "
ssh_only = true

[jobs]
format = "[$symbol$number]($style) "
style = "bold context"

[lua]
format = "[$symbol$version]($style) "
style = "bold context"

[nix_shell]
format = "[via](muted) [$symbol$name]($style) "
heuristic = true
style = "bold context"
symbol = " "

[package]
format = "[$symbol$version]($style) "
style = "bold context"
symbol = " "

[palettes.modus]
context = "#79a8ff"
duration = "#feacd0"
error = "#ff7f9f"
frame = "#d2b580"
muted = "#989898"
path = "#00d3d0"
prompt = "#b6a0ff"
remote = "#6ae4b9"
success = "#6ae4b9"
warning = "#ff9f80"

[python]
format = "[$symbol$pyenv_prefix($version )(($virtualenv) )]($style)"
style = "bold context"

[rust]
format = "[$symbol$version]($style) "
style = "bold context"

[status]
disabled = false
format = "[┫](bold frame)[$status](bold error)[┣](bold frame)"
